Mejoras schema y proxy reverso en Swagger
SIU-Toba/rest pull request #21
Opened 2022-07-26 20:12 UTC by lleonardis

https://swagger.io/docs/specification/data-models/data-types/#array
https://foro.comunidad.siu.edu.ar/index.php?topic=24504.msg111379#msg111379

2022-07-27 13:29 UTC, enfoqueNativo requested changes

2022-07-27 13:29 UTC, enfoqueNativo commented on src/SIUToba/rest/lib/modelo_recursos.php
> +						$campo_def['$ref'] = '#/components/schemas/'. trim($campo_def['$ref']);
Ya existe una funcion para esto, usarla.

2022-07-27 13:29 UTC, enfoqueNativo commented on src/SIUToba/rest/http/request.php
> +            || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')
Todo esto hay que repensarlo, no tiene sentido que la libreria analice los headers que envia el cliente. 

Es mas, lo separaria en un PR aparte, porque necesita tomarse en cuenta con modificaciones a  `rest.php`

2022-07-27 18:31 UTC, lleonardis commented on src/SIUToba/rest/lib/modelo_recursos.php
> +						$campo_def['$ref'] = '#/components/schemas/'. trim($campo_def['$ref']);
@enfoqueNativo Ya lo cambie, estoy usando la función **get_tipo_datos** de  **src/SIUToba/rest/docs/tipo_datos_docs.php**, ¿así seria?

2022-07-27 18:37 UTC, lleonardis commented on src/SIUToba/rest/http/request.php
> +            || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')
@enfoqueNativo Ya lo deshice, ¿como seria crear otro pull request? ¿tengo que crear una feature en mi repo forkeado?

2022-07-27 20:16 UTC, enfoqueNativo commented on src/SIUToba/rest/http/request.php
> +            || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')
Create otra rama y haces un nuevo PR.. igual tene en cuenta lo que te decia antes, asi como lo subiste no va.

2022-08-02 19:59 UTC, enfoqueNativo commented on src/SIUToba/rest/lib/modelo_recursos.php
> +                }
```suggestion
               switch ($k) {
                    case 'type':
                        $prop = array_merge($prop, tipo_datos_docs::get_tipo_formato($campo_def));
                        break;
                    case 'items':
                        if (! is_array($campo_def)) {
                            $prop[$k] = tipo_datos_docs::get_tipo_datos($campo_def); 
                        } else{
                            $definicion = (isset($campo_def['$ref'])) ? '$ref:'.$campo_def['$ref'] : current($campo_def); 
                            $prop[$k] = tipo_datos_docs::get_tipo_datos($definicion); 
                        }
                        break;
                    default:
                        $prop[$k] = $campo_def;    
                } 
```

2022-08-03 20:32 UTC, lleonardis commented on src/SIUToba/rest/lib/modelo_recursos.php
> +                }
@enfoqueNativo Funciona bien en la API de personas!!!

2022-09-22 20:20 UTC, enfoqueNativo approved these changes

2022-09-22 20:23 UTC, merged